### ISSUE TITLE
Chore: Add more detail to bio/intro

### ISSUE THREAD

**Issue by nelsonic** [SimonLab/SimonLab#1]
At present you have a nice profile picture and basic intro:
<img width="1327" alt="image" src="https://github.com/SimonLab/SimonLab/assets/194400/734e4092-d261-4473-96b9-785f9ab704f3">

# Todo:

+ [ ] Consider updating the `aws-sdk-mock` to `TypeScript`: https://github.com/dwyl/aws-sdk-mock/pull/277 🧑‍💻 🙏  (paid!)
  + [x] @nelsonic to add @SimonLab as colaborator/publisher on NPM: https://www.npmjs.com/package/aws-sdk-mock ➕ 
  + [ ] @SimonLab to publish `new` version once the `TypeScript` update is complete. 📦 :shipit: 
  > **Note**: current downloads per month of `aws-sdk-mock`: 420,095 x 52 / 12 = 1.8m/month 📈 
  + [ ] Add repo to your profile pinned repos. 📍

+ [ ] Add copy to the effect of:

I'm Simon, a full stack software engineer. 
In my 8 years as an engineer I've build and maintained many projects.
Open Source Code I've written/maintained is used by 60% of Fortune 500 companies and has Millions of downloads per month.
Comfortable with several programming languages including: `JavsScript`/`TypeScript`, `Elm`, `Haskell`, `Python`, `SQL` and `Elixir`. 
Currently working with `Elixir`, `Phoenix` and `LiveView`! 
Also learning `ML` and playing with `LLMs`.
AMA. 

<hr />

I _know_ it feels "weird" to self-promote. But ultimately if you want to move forward you _have_ to do it. 
You can always remove it once you've got the job you want. 👌

**Comment by nelsonic** [comment]
@SimonLab please LMK what your NPM username is so that I can add you as a maintainer. 🙏

**Comment by SimonLab** [comment]
Just tried to loggedin again with npm (for a while) and unfortunately I'm not able to access my account as it requires to "Enter One-time Password" which has been sent to my old dwyl.io email address.

![image](https://github.com/SimonLab/SimonLab/assets/6057298/f649f0f4-59b5-4f9b-addf-286f8db36abb)

I'll see if I can recover my account, otherwise I might need to create a new one
![image](https://github.com/SimonLab/SimonLab/assets/6057298/6fdaa9c9-366b-48b6-9837-90c07949cf89)

**Comment by nelsonic** [comment]
@SimonLab contact NPM support and inform them that `@dwyl.io` is your old work email address 
and you need to recover your account. 
They're usually pretty responsive with these kinds of things. 🤞

**Comment by SimonLab** [comment]
@nelsonic working now, npm username: simonlab

**Comment by nelsonic** [comment]
Invite sent: https://www.npmjs.com/package/aws-sdk-mock/access
<img width="1491" alt="image" src="https://github.com/SimonLab/SimonLab/assets/194400/a3a46c82-cb4d-4de0-afb5-94f67b0e44c0">

You'll need to have 2FA enabled to accept. 

Once you've accepted, Please take a look at: https://github.com/dwyl/aws-sdk-mock/issues/287
(You can always publish a newer version with `HypeScript` once you feel confident in your skills ...)

Then consider updating your avatar to your "on brand" GitHub profile pic:
https://www.npmjs.com/~simonlab
<img width="1139" alt="image" src="https://github.com/SimonLab/SimonLab/assets/194400/6042c64a-8550-4668-bd8f-cae99122c08f">

**Comment by nelsonic** [comment]
Merging this PR: https://github.com/dwyl/aws-sdk-mock/pull/289 should get you on the [Scoreboard](https://github.com/dwyl/aws-sdk-mock/graphs/contributors) 😉 
Then it's up to you how much you want to contribute in terms of `code`. 🧑‍💻 ⏳ 
Meanwhile you can name-drop that ***`NASA`*** is using a package that you co-maintain. 😜
